### ISSUE TITLE
Compiling using Platformio failing

### ISSUE THREAD

**Issue by meauxt** [Seeed-Studio/Grove_Human_Presence_Sensor#2] opened 2020-03-20 16:04 UTC
whenever i just import the library am getting the following error
`Compiling .pio/build/esp32/FrameworkArduino/Esp.cpp.o
.pio/libdeps/esp32/Grove Human Presence Sensor Library_ID6523/Grove_Human_Presence_Sensor.cpp: In constructor 'Smoother::Smoother(float)':
.pio/libdeps/esp32/Grove Human Presence Sensor Library_ID6523/Grove_Human_Presence_Sensor.cpp:402:9: error: 'Smoother::m_average_weight' will be initialized after [-Werror=reorder]
   float m_average_weight;
         ^
.pio/libdeps/esp32/Grove Human Presence Sensor Library_ID6523/Grove_Human_Presence_Sensor.cpp:401:9: error:   'float Smoother::m_last_marked_value' [-Werror=reorder]
   float m_last_marked_value;
         ^
.pio/libdeps/esp32/Grove Human Presence Sensor Library_ID6523/Grove_Human_Presence_Sensor.cpp:380:3: error:   when initialized here [-Werror=reorder]
   Smoother(float average_weight) : 
   ^
.pio/libdeps/esp32/Grove Human Presence Sensor Library_ID6523/Grove_Human_Presence_Sensor.cpp: At global scope:
.pio/libdeps/esp32/Grove Human Presence Sensor Library_ID6523/Grove_Human_Presence_Sensor.cpp:411:29: error: default argument given for parameter 4 of 'PresenceDetector::PresenceDetector(AK9753&, float, float, int)' [-fpermissive]
     int detect_interval = 30) :
                             ^
In file included from .pio/libdeps/esp32/Grove Human Presence Sensor Library_ID6523/Grove_Human_Presence_Sensor.cpp:30:0:
.pio/libdeps/esp32/Grove Human Presence Sensor Library_ID6523/Grove_Human_Presence_Sensor.h:189:3: note: previous specification in 'PresenceDetector::PresenceDetector(AK9753&, float, float, int)' here
   PresenceDetector(
   ^
.pio/libdeps/esp32/Grove Human Presence Sensor Library_ID6523/Grove_Human_Presence_Sensor.cpp: In destructor 'PresenceDetector::~PresenceDetector()':
.pio/libdeps/esp32/Grove Human Presence Sensor Library_ID6523/Grove_Human_Presence_Sensor.cpp:428:12: warning: deleting array '((PresenceDetector*)this)->PresenceDetector::m_smoothers'
   delete[] m_smoothers;
            ^
cc1plus: some warnings being treated as errors
*** [.pio/build/esp32/lib812/Grove Human Presence Sensor Library_ID6523/Grove_Human_Presence_Sensor.cpp.o] Error 1`

am using ESPhone ( internally use platformio) and getting same result when i do it from platformio

**Comment by ackPeng** [comment] 2024-10-16 07:52
@meauxt  You should have enabled -Werror in your compiler options. The compiler option -Werror will treat all warnings as errors. This is helpful for debugging and improving code quality, but it can sometimes cause unnecessary obstacles during development. Temporarily disabling the -Werror option to allow warnings not to be the cause of compilation failures may resolve these errors

**Comment by Lesords** [comment] 2024-10-30 10:59
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]

**Closed as completed by Lesords** 2024-10-30 10:59 UTC
Labels: UAY, Grove_Human_Presence_Sensor
